services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db 
    env_file:
      - mongo.env
    ports:
      - "27017:27017"
  frontend:
    build: ./frontend
    env_file:
      - front.env
    ports:
      - "8080:8080"
    restart: always
    links:
      - backend
  backend:
    build: ./backend
    env_file:
      - back.env
    ports:
      - "8000:8000"
    restart: always
    links:
      - mongo