version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - mongo.env
    ports:
      - "27017:27017"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - front.env
    ports:
      - "8080:8080"
    restart: always
    links:
      - backend
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    env_file:
      - back.env
    ports:
      - "8000:8000"
    restart: always
    links:
      - mongo