services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db 
    env_file:
      - mongo.env
    ports:
      - "27017:27017"
  frontend:
    build: 
      context: ./frontend
      args:
      - NODE_ENV=${NODE_ENV}
      - VUE_APP_GOOGLE_CLIENT_ID=${VUE_APP_GOOGLE_CLIENT_ID}
    ports:
      - "8080:8080"
    restart: always
    links:
      - backend
  backend:
    build: ./backend
    env_file:
      - back.env
    ports:
      - "8000:8000"
    restart: always
    links:
      - mongo