apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.front.name }}
data:
  .env: |
  {{- range $k, $v := .Values.front.envs }}
  {{- if kindIs "string" $v }}
    {{ $k | upper }}={{ $v | quote }}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.back.name }}
data:
{{- range $k, $v := .Values.back.envs }}
{{- if kindIs "string" $v }}
  {{ $k | upper }}: {{ $v | quote }}
{{- end }}
{{- end }}