apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.front.name }}
  labels:
    app: {{ .Values.front.name }}
spec:
  type: {{ .Values.front.service.type }}
  ports:
  - port: {{ .Values.front.service.port }}
    targetPort: {{ .Values.front.port }}
    protocol: TCP
  selector:
    app: {{ .Values.front.name }}
