apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: {{ .Values.back.service.type }}
  ports:
  - port: {{ .Values.back.service.port }}
    targetPort: {{ .Values.back.port }}
    protocol: TCP
  selector:
    app: backend
