name: Conditional Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  # Backend Job
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check changes in backend
        id: changes-backend
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "^backend/"; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Build and Push Backend Image
        if: ${{ env.changed == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/backend:latest
            ghcr.io/${{ github.repository_owner }}/backend:${{ github.sha }}

  # Frontend Job
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check changes in frontend
        id: changes-frontend
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "^frontend/"; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Build and Push Frontend Image
        if: ${{ env.changed == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/frontend:latest
            ghcr.io/${{ github.sha }}
