name: Conditional Build and Push Docker Images

on:
  push:
    branches:
      - main
      - develop

jobs:
  # Backend Job
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Docker Tags
        id: docker_tags
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "TAGS=ghcr.io/${{ github.repository_owner }}/backend:latest,ghcr.io/${{ github.repository_owner }}/backend:${{ github.sha }}" >> $GITHUB_ENV
          else
            echo "TAGS=ghcr.io/${{ github.repository_owner }}/backend:develop,ghcr.io/${{ github.repository_owner }}/backend:${{ github.sha }}" >> $GITHUB_ENV
          fi
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          tags: ${{ env.TAGS }}

  # Frontend Job
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Docker Tags
        id: docker_tags
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "TAGS=ghcr.io/${{ github.repository_owner }}/frontend:latest,ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }}" >> $GITHUB_ENV
          else
            echo "TAGS=ghcr.io/${{ github.repository_owner }}/frontend:develop,ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }}" >> $GITHUB_ENV
          fi
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: frontend
          push: true
          tags: ${{ env.TAGS }}
          build-args: |
            NODE_ENV=${{ secrets.NODE_ENV }}
            VUE_APP_GOOGLE_CLIENT_ID=${{ secrets.VUE_APP_GOOGLE_CLIENT_ID }}
